/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface PwnedPassword {
    'minlength': number;
    'name': string;
    'pattern': string;
    'placeholder': string;
  }
  interface PwnedPasswordAttributes extends StencilHTMLAttributes {
    'minlength'?: number;
    'name'?: string;
    /**
    * Emitted when a result is received from api.pwnedpasswords.com
    */
    'onPwnedPasswordFound'?: (event: CustomEvent<number>) => void;
    'pattern'?: string;
    'placeholder'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'PwnedPassword': Components.PwnedPassword;
  }

  interface StencilIntrinsicElements {
    'pwned-password': Components.PwnedPasswordAttributes;
  }


  interface HTMLPwnedPasswordElement extends Components.PwnedPassword, HTMLStencilElement {}
  var HTMLPwnedPasswordElement: {
    prototype: HTMLPwnedPasswordElement;
    new (): HTMLPwnedPasswordElement;
  };

  interface HTMLElementTagNameMap {
    'pwned-password': HTMLPwnedPasswordElement
  }

  interface ElementTagNameMap {
    'pwned-password': HTMLPwnedPasswordElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
